module Rubicon::Frostbite::BF3

    # Allows us to have a special player object for any events which are 
    # emitted by the game server without it polluting the actual collection.
    class PlayerCollection < Hash
        def initialize(server)
            @server_player = SpecialPlayer.new(server, "Server")
            super()
        end

        def [](key)
            key == "Server" ? @server_player : super(key)
        end

        def []=(key, value)
            key == "Server" ? value : super(key, value)
        end

        # Converts this player collection and all its players into a hash.
        # Useful for converting to JSON
        def to_hash
            ret = {}

            each do |name, player|
                ret[name] = player.to_hash
            end

            ret
        end
    end

    class Player
        NO_GUID = "NO_GUID"

        attr_accessor :name, :guid, :score, :kills,
            :deaths, :rank

        def initialize(server, name, guid=NO_GUID)
            @server = server
            @name = name
            @guid = guid

            @team_id = 0
            @squad_id = 0

            @kills = 0
            @deaths = 0
            @rank = 0
            @score = 0

            team.add self
            squad.add self
        end

        def team
            @server.teams[@team_id]
        end

        def team=(new_team)
            if new_team.is_a?(Integer) && new_team.between?(0, 16)
                # removing from a team also removes from the squad
                return if @team_id == new_team
                team.remove self.name
                @team_id = new_team
                team.add self
                # adding to a team also adds to the squad
            elsif new_team.is_a? Team
                return if @team_id == new_team.id
                # TODO: make this issue a move command if a team object
                # is passed, as likely it will be done by a script
                team = new_team.id
            else
                raise "#{new_team} is not a valid team!"
            end
        end

        def squad
            @server.teams[@team_id].squads[@squad_id]
        end

        # Used by Team#add to move the player to the appropriate squad
        def squad_id
            @squad_id
        end

        def squad=(new_squad)
            if new_squad.is_a?(Integer) && new_squad.between?(0, 32)
                return if @squad_id == new_squad
                squad.remove self.name
                @squad_id = new_squad
                squad.add self
            elsif new_squad.is_a? Squad
                return if @squad_id == new_squad.id
                # TODO: make this issue a move command if a squad object
                # is passed, as likely it will be done by a script
                squad = new_squad.id
            else
                raise "#{new_squad} is not a valid squad!"
            end
        end

        # Says `msg` to every player's chatbox.
        def say(msg)
            @server.send_command("admin.say", msg, "player", @name)
        end

        # Yells `msg` to the entire server for `duration` seconds.
        def yell(msg, duration)
            @server.send_command("admin.yell", msg, duration, "player", @name)
        end

        # Kick a player. If a reason is not passed, it will default to the BF3 server's
        # default value of "Kicked by administrator."
        def kick(reason=nil) 
            if reason
                @server.send_command("admin.kickPlayer", @name, reason)
            else
                @server.send_command("admin.kickPlayer", @name)
            end
        end

        # Kill the player.
        def kill
            @server.send_command("admin.killPlayer", @name)
        end

        # Stubbed out to return true until a permissions system is implemented
        def has_permission? (perm)
            true
        end

        # Checks if the player is actually in the server. This is assumed to be the
        # case if the server has sent a onJoin event for the player, thus setting
        # their GUID to something other than the default of NO_GUID
        def has_joined?
            @guid != NO_GUID
        end

        # Should return true for actual humans who triggered the event.
        # Will return false if the event has generated by a machine, such as
        # the console or the game server itself.
        #
        # NOTE: This function cannot currently detect aimbots.
        def is_human?
            true
        end

        # Pretty print like a boss
        def inspect
            "#<BF3Player: #{@name} #{@kills}/#{@deaths} #{@score}>"
        end

        def disconnected
            squad.remove @name
            team.remove @name
        end

        def has_permission?(perm_name)
            @server.permissions_manager.player_has_permission?(@name, perm_name)
        end

        def belongs_to_group?(group_name)
            @server.permissions_manager.player_belongs_to_group?(@name, group_name)
        end

        def ping
            ping_packet = @server.send_request("player.ping", @name)
            if ping_packet.words[0] == "OK"
                ping_packet.words[1].to_i
            else
                -1
            end
        end

        # Converts this player to a Hash. Useful for things like JSON serialization
        def to_hash
            {
                name:   @name,
                team:   @team_id,
                squad:  @squad_id,
                kills:  @kills,
                deaths: @deaths,
                rank:   @rank,
                score:  @score
            }
        end
    end

    # A special player is used for any commands or events sent by the console or the
    # game server itself. It has every permission and returns `false` for `is_human?`
    class SpecialPlayer < Player
        def initialize(server, name, guid=NO_GUID)
            @server = server
            @name = name
            @guid = guid

            @team_id = 0
            @squad_id = 0

            @kills = 0
            @deaths = 0
            @rank = 0
            @score = 0
        end

        def has_permission?(perm)
            true
        end

        def is_human?
            return false
        end
    end
end